---
########### USE ECS MGMT API with ECS_TESTDRIVE ACCOUNT #############
- name: ECS create new S3 bucket with management API
  hosts: ecs_testdrive
  gather_facts: False
  vars:
    username: '<username>'
    password: '<password>'
    ECS_host: 'portal.ecstestdrive.com'
    NameSpace: '<namespace>'
    bucketOwner: "{{NameSpace}}@ecstestdrive.emc.com"
    BucketName: myAnsible_ECSmgmt_Bucket

  tasks:

  - name: Get ECS API authentication token
    uri:
      validate_certs: no
      user: "{{ username }}"
      password: "{{ password }}"
      url: https://{{ECS_host}}/login
      method: GET
      headers:
        Content-Type: application/json
        Accept: application/json
      return_content: yes
    register: results_login
    no_log: True


  - name: Connect to ECS | create new bucket {{ BucketName }}
    uri:


  - debug:
