---
########### USE ECS MGMT API #############
- name: ECS Delete bucket with management API
  hosts: ecs_testdrive
  gather_facts: False
  vars:
    username: "131887216500386603-admin"
    password: "Mzc1ZjhjYTE5YzgwMDQ3NWRkNmMwMDA4NjZkODI5NzM="
    ECS_host: "portal.ecstestdrive.com"
    bucketOwner: "131887216500386603-admin"

    BucketName: myAnsible_ECSmgmt_Bucket
    NameSpace: '131887216500386603'

  tasks:

  - name: Get ECS API authentication token
    uri:
      validate_certs: no
      user: "{{ username }}"
      password: "{{ password }}"
      url: https://{{ECS_host}}/login
      method: GET
      headers:
        Content-Type: application/json
        Accept: application/json
      return_content: yes
    register: results_login
#   no_log: True

  - name: Connect to ECS | delete bucket {{ BucketName }}
    uri:
      validate_certs: no
      url: "https://{{ECS_host}}/object/bucket/{{ BucketName }}/deactivate.json"
      method: POST
      headers:
        Content-Type: application/json
        Accept: application/json
        X-SDS-AUTH-TOKEN: "{{ results_login.x_sds_auth_token }}"
      body_format: json
      return_content: yes
    register: results_DeleteBucket

  - debug:
     msg="{{ results_DeleteBucket }}"
