---
- name: "Install ftp and specified package"
  hosts: centos
  vars:
    package: telnet

  tasks:

    - name: Install ftp
      yum:
        name: ftp
        state: present
    
    - name: Install "{{ package }}"
      yum:
        name: "{{ package }}"
        state: present

