---
########## REQUIRES PYTHON3 and BOTO3 #############
- name: ECS Create S3 bucket
  hosts: ecs_testdrive
  gather_facts: False
  vars:
    username: "<username>@ecstestdrive.emc.com"
    password: "secretkey"
    ECS_host: "object.ecstestdrive.com"

  tasks:

    - name: Connect to ECS | Create S3 bucket
      aws_s3:
        bucket: ansible_aws_s3_bucket
        mode: create
        permission: public-read
        s3_url: https://{{ ECS_host }}/
        validate_certs: no
        encrypt: no
        rgw: true
        aws_access_key: "{{ username }}"
        aws_secret_key: "{{ password }}"
      register: results_CreateBucket

    - debug:
        msg="{{ results_CreateBucket }}"

